#!/bin/sh

docker run --rm -it \
	-v "$GOPATH":/gopath \
	-v "$(pwd)":/app \
	-e "GOPATH=/gopath" \
	-w /app \
	golang:1.8.1-alpine \
	sh -c 'CGO_ENABLED=0 go build -a --installsuffix cgo --ldflags="-s -w" -o main'
