#!/bin/bash

# build_aar "$@"
source $NDK_BUILD_UTILS_DIR/build_aar.sh

echo "aar build env:"
echo "GOLANG_VERSION      ${GOLANG_VERSION}"
echo "ANDROID_SDK_VERSION ${ANDROID_SDK_VERSION}"
echo "ANDROID_NDK_VERSION ${ANDROID_NDK_VERSION}"
echo "SODIUM_VERSION      ${SODIUM_VERSION}"
echo "OPUS_VERSION        ${OPUS_VERSION}"
echo "VPX_VERSION         ${VPX_VERSION}"
echo "TOXCORE_VERSION     ${TOXCORE_VERSION}"

# for test
# go_archs=(arm)

build_aar "$@"
